# Generated by Django 6.0.2 on 2026-02-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_seller_logo'),
        ('products', '0003_productimage_is_main_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, choices=[('easy', 'oson'), ('medium', 'o‘rta'), ('hard', 'murakkab')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='light',
            field=models.CharField(blank=True, choices=[('sun', 'quyosh'), ('shade', 'soya'), ('half', 'yarim soyali')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, choices=[('S', '30 sm gacha'), ('M', '30–70 sm'), ('L', '70–150 sm'), ('XL', '150 sm dan yuqori')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.seller'),
        ),
    ]
