# Generated by Django 6.0.2 on 2026-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_diameter_product_care_product_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'complex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, choices=[('S', 'up to 30 cm'), ('M', '30–70 cm'), ('L', '70–150 cm'), ('XL', 'above 150 cm')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='light',
            field=models.CharField(blank=True, choices=[('sun', 'sun'), ('shade', 'shade'), ('half', 'partial shade')], max_length=10),
        ),
    ]
