# Generated by Django 6.0.2 on 2026-03-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='my_works',
        ),
        migrations.CreateModel(
            name='GardenWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gardens/works/')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='services.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.service')),
            ],
        ),
        migrations.AlterField(
            model_name='garden',
            name='services',
            field=models.ManyToManyField(related_name='gardens', to='services.service'),
        ),
        migrations.DeleteModel(
            name='ChildService',
        ),
        migrations.DeleteModel(
            name='ParentService',
        ),
    ]
